server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: users
          uri: lb://USERS
          predicates:
            - Path=/api/v1/user/**
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/v1/notification/**

management:
  tracing:
    enabled: true
    sampler:
      probability: 1.0

eureka:
  instance:
    appname: apigw
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
