spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8761

management:
  tracing:
    enabled: true
    sampler:
      probability: 1.0


eureka:
  client:
    fetch-registry: false #false since this is the server itself
    register-with-eureka: false #false since this is the server itself
    service-url:
      defaultZone: http://localhost:8761/eureka/
