spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8761
eureka:
  client:
    fetch-registry: false #false since this is the server itself
    register-with-eureka: false #false since this is the server itself
    service-url:
      defaultZone: http://localhost:8761/eureka/
