server:
  port: 8087

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  application:
    name: report
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/report
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false


management:
  tracing:
    enabled: true
    sampler:
      probability: 1.0


eureka:
  instance:
    appname: report
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
